= InteractiveLabeler
Algis Dumbris <a.dumbris@gmail.com>
v1.0
:toc: left
:imagesdir: assets/images

== Introduction
This document describes project for 

=== Update service

To update run command

[source,bash]
make update-prod


== Architecture overview

=== How InteractiveLabeler works

[plantuml, diagram-classes, png]
....
@startuml push_task
title __General idea__ of communication an arbitrary python code\nand InteractiveLabeler component

actor User as U
participant "Python Code" as P
participant "Embedded Server" as S
participant "Web Client" as C

U --> P: User starts \npython script
... script do some computations ...

P -> S: with InteractiveLabeler() as il:
activate S #FFBBBB
note over of S
Embedded web server will be started 
in the other thread. 
The script will continue to execute.
end note

P -> S: y = il.make_query(X)
activate P #grey
note over of P
The script will be stopped 
at this point and 
will wait for __make_query()__ function results
end note

S -> C: task {type:}
C --> U: show samples
... actual labeling process ...
C <-- U: save labels
C -> S : push solution
P <- S : send data back
deactivate P
note over of P
Script continue to execute
end note
... script do some computations ...
@enduml
....

== Protocol details
include::protocol.adoc[]

// vim: set syntax=asciidoc:
